/*
 * Copyright (C) 2008-2009 Daniel Prevost <dprevost@photonsoftware.org>
 *
 * This file is part of Photon (photonsoftware.org).
 *
 * This file may be distributed and/or modified under the terms of the
 * GNU General Public License version 2 or version 3 as published by the 
 * Free Software Foundation and appearing in the file COPYING.GPL2 and 
 * COPYING.GPL3 included in the packaging of this software.
 *
 * Licensees holding a valid Photon Commercial license can use this file 
 * in accordance with the terms of their license.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 */

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

#include "Common/Common.h"
#include <photon/photon>
#include <iostream>

using namespace std;
using namespace pso;


/* 
 * This test is for ticket 1836613. It seems that psoExitSession() is not
 * closing open objects - the bug will be seen when the session is reopen
 * and a new attempt will be made to create the object. This attempt should 
 * work since in the previous pass:
 *   - the object was created but not committed
 *   - an automated rollback was perform with ExistSession()
 *   - an automated close object was performed with psoExitSession (which
 *     should put all ref. counters to zero, deleting the object from 
 *     shared memory)
 *
 * Note: for c++, we must do it a bit differently as there is no exit()
 *       function for sessions - it is implicitely called by the destructor.
 */
 
/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

int main( int argc, char * argv[] )
{
   Process process;
   Session * session = NULL;
   Folder * folder = NULL;
   string name = "/cpp_session_exit";
   psoObjStatus status;

   try {
      if ( argc > 1 ) {
         process.Init( argv[1], argv[0] );
      }
      else {
         process.Init( "10701", argv[0] );
      }
   }
   catch( pso::Exception exc ) {
      cerr << "Test failed in init phase, error = " << exc.Message() << endl;
      cerr << "Is the server running?" << endl;
      return 1;
   }

   try {
      session = new Session();
      folder = new Folder();
      
      session->Init();
      session->CreateFolder( name );
      folder->Open( *session, name );
      
      delete session;
   }
   catch( pso::Exception exc ) {
      cerr << "Test failed - line " << __LINE__ << ", error = " << exc.Message() << endl;
      return 1;
   }

   
   // Try to use the folder object. 
   try {
      folder->Status( status );
      // Should never come here
      cerr << "Test failed - line " << __LINE__ << endl;
      return 1;
   }
   catch( pso::Exception exc ) {
      return 0;
   }

   cerr << "Test failed - line " << __LINE__ << endl;
   return 1;
}

/* --+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+-- */

